name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-cli:
    name: Build CLI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Use Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - run: cargo build -p exrtool-cli --release
      - uses: actions/upload-artifact@v3
        with:
          name: exrtool-cli-${{ matrix.os }}
          path: target/release/exrtool-cli*

  build-gui:
    name: Build Tauri GUI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: tauri-apps/setup-tauri@v1
      - run: cargo build --release --manifest-path apps/exrtool-gui/src-tauri/Cargo.toml
      - uses: actions/upload-artifact@v3
        with:
          name: exrtool-gui-${{ matrix.os }}
          path: apps/exrtool-gui/src-tauri/target/release/exrtool-gui*

  lint:
    name: Lint (fmt + clippy)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt, clippy
      - name: cargo fmt --check
        run: cargo fmt --all -- --check
      - name: cargo clippy -D warnings
        run: cargo clippy --workspace --all-targets -- -D warnings

  features:
    name: Feature Matrix (core)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: use_exr_crate
        run: cargo check -p exrtool-core --features use_exr_crate
