name: Build Packages

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Install Tauri CLI
        run: cargo install tauri-cli --locked
      - name: Build Windows packages
        shell: pwsh
        run: ./scripts/package_windows.ps1

  macos:
    runs-on: macos-latest
    env:
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Install Tauri CLI
        run: cargo install tauri-cli --locked
      - name: Build macOS package
        run: ./scripts/package_macos.sh

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libayatana-appindicator3-dev
      - name: Install Tauri CLI
        run: cargo install tauri-cli --locked
      - name: Build AppImage
        run: ./scripts/package_linux.sh
